# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
 workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    - name: Tag
      id: autotagger
      uses: butlerlogic/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      
    - name: Release
      id: create_release
      if: steps.autotagger.outputs.tagname != ''
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.autotagger.outputs.tagname }}
        release_name: Version ${{ steps.autotagger.outputs.version }}
        body: ${{ steps.autotagger.outputs.tagmessage }}
        draft: false
        prerelease: true

    - name: Publish
      id: publish_npm
      if: steps.autotagger.outputs.tagname != ''
      uses: author/action-publish@stable
      env:
        REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

    - name: Rollback Release
      if: failure() && steps.create_release.outputs.id != ''
      uses: author/action-rollback@stable
      with:
        # Using a known release ID
        id: ${{ steps.create_release.id }}
        # Using a tag name
        tag: ${{ steps.autotagger.outputs.tagname }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
